---
- name: "find line"
  lineinfile:
    state: absent
    path: "{{ filepath }}"
    insertafter: "{{ insert_after }}"
    regexp: "{{ regexp }}"
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check
- name: "append line"
  lineinfile:
    state: present
    path: "{{ filepath }}"
    insertafter: "{{ insert_after }}"
    line: "{{ line }}"
  when: check.found == 0


