---
- name: "prereqs"
  hosts: servers
  environment:
    OS_PROJECT_DOMAIN_NAME: default
    OS_USER_DOMAIN_NAME: default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: "{{keystone_admin_password}}"
    OS_AUTH_URL: http://{{controller_hostname}}:5000/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
  roles:
    - role: prereqs
      tags: ["prereqs", "core"]
      vars:
        hostname: controller_node
    - role: config_databases
      tags: ["prereqs", "core", "database"]
    - role: keystone
      tags: ["core", "keystone"]
    - role: glance
      tags: ["core","glance"]
    - role: placement
      tags: ["core", "placement"]
    - role: nova
      tags: ["core", "nova"]
    - role: neutron
      tags: ["core", "neutron"]
    - role: horizon
      tags: ["horizon", "dashboard"]
