nova_configs:
  api: |
    auth_strategy = keystone
  DEFAULT: |
    osapi_compute_listen = 127.0.0.1
    osapi_compute_listen_port = 8774
    metadata_listen = 127.0.0.1
    metadata_listen_port = 8775
    state_path = /var/lib/nova
    enabled_apis = osapi_compute,metadata
    log_dir = /var/log/nova
    transport_url = "rabbit://openstack:{{rabbitmq_db_pass}}@{{controller_hostname}}"
    compute_driver = libvirt.LibvirtDriver
  vnc: |
    enabled = True
    novncproxy_host = 127.0.0.1
    novncproxy_port = 6080
    novncproxy_base_url = "http://{{controller_hostname}}:6080/vnc_auto.html"
  glance: |
    api_servers = "http://{{controller_hostname}}:9292"
  oslo_concurrency: |
    lock_path = $state_path/tmp
  api_database: |
    connection = "mysql+pymysql://nova:{{nova_db_pass}}@{{controller_hostname}}/nova_api"
  database: |
    connection = "mysql+pymysql://nova:{{nova_db_pass}}@{{controller_hostname}}/nova"
  keystone_authtoken: |
    www_authenticate_uri = "http://{{controller_hostname}}:5000"
    auth_url = "http://{{controller_hostname}}:5000"
    memcached_servers = "{{controller_hostname}}:11211"
    auth_type = password
    project_domain_name = default
    user_domain_name = default
    project_name = service
    username = nova
    password = "{{nova_pass}}" 
  placement: |
    auth_url = "http://{{controller_hostname}}:5000"
    os_region_name = RegionOne
    auth_type = password
    project_domain_name = default
    user_domain_name = default
    project_name = service
    username = placement
    password = "{{placement_pass}}"
