placement_configs:
  api: |
      auth_strategy = keystone
  DEFAULT: |
      debug = false
  keystone_authtoken: |
      www_authenticate_uri = "http://{{controller_hostname}}:5000"
      auth_url = "http://{{controller_hostname}}:5000"
      memcached_servers = "{{controller_hostname}}:11211"
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      project_name = service
      username = placement
      password = "{{placement_pass}}"
  placement_database: |
      connection = "mysql+pymysql://placement:{{placement_db_pass}}@{{controller_hostname}}/placement"
