neutron_configs:
  DEFAULT: |
    core_plugin = ml2
    service_plugins = router
    allow_overlapping_ips = true
    transport_url = rabbit://openstack:password@controller
    auth_strategy = keystone
    notify_nova_on_port_status_changes = true
    notify_nova_on_port_data_changes = true
  nova: |
    auth_url = http://controller:5000
    auth_type = password
    project_domain_name = default
    user_domain_name = default
    region_name = RegionOne
    project_name = service
    username = nova
    password = servicepassword
  oslo_concurrency: |
    lock_path = /var/lib/neutron/tmp
  database: |
    connection = mysql+pymysql://neutron:password@controller/neutron
  keystone_authtoken: |
    www_authenticate_uri = http://controller:5000
    auth_url = http://controller:5000
    memcached_servers = controller:11211
    auth_type = password
    project_domain_name = default
    user_domain_name = default
    project_name = service
    username = neutron
    password = servicepassword

ml2_configs:
  ml2: |
    type_drivers = flat,vlan,vxlan
    tenant_network_types = vxlan
    mechanism_drivers = linuxbridge,l2population
    extension_drivers = port_security
  ml2_type_flat: |
    flat_networks = provider
  ml2_type_vxlan: |
    vni_ranges = 1:1000
  securitygroup: |
    enable_ipset = true

linuxbridge_configs:
  linux_bridge: |
    physical_interface_mappings = provider:enp9s0
  vxlan: |
    enable_vxlan = true
    local_ip = 10.10.10.147
    l2_population = true
  securitygroup: |
    enable_security_group = true
    firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver

l3_agent_configs:
  DEFAULT: |
    interface_driver = linuxbridge

dhcp_agent_configs:
  DEFAULT: |
    interface_driver = linuxbridge
    dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq
    enable_isolated_metadata = true

metadata_agent_configs:
  DEFAULT: |
    nova_metadata_host = controller
    metadata_proxy_shared_secret = secret

nova_configs:
  neutron: |
    auth_url = http://controller:5000
    auth_type = password
    project_domain_name = default
    user_domain_name = default
    region_name = RegionOne
    project_name = service
    username = neutron
    password = servicepassword
    service_metadata_proxy = true
    metadata_proxy_shared_secret = secret
