glance_configs:
  DEFAULT: |
    transport_url = "rabbit://openstack:{{rabbitmq_db_pass}}@{{controller_hostname}}"
  database: |
    connection = "mysql+pymysql://glance:{{glance_db_pass}}@{{controller_hostname}}/glance"
  glance_store: |
    stores = file,http
    default_store = file
    filesystem_store_datadir = /var/lib/glance/images/
  keystone_authtoken: |
    www_authenticate_uri = "http://{{controller_hostname}}:5000"
    auth_url = "http://{{controller_hostname}}:5000"
    memcached_servers = "{{controller_hostname}}:11211"
    auth_type = password
    project_domain_name = default
    user_domain_name = default
    project_name = service
    username = glance
    password = "{{glance_pass}}"
  paste_deploy: |
    flavor = keystone
