---
- name: "Install keystone packages"
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-keystone 
    - httpd 
    - mod_wsgi
- name: "Update openstacksdk package to the latest"
  pip:
    name: openstacksdk
    state: latest
    #- name: Loop over subelements of the dictionary
    #  debug:
    #    msg: "Key={{ item.0.key }} secondary_key={{ item.1 }}"
    #  loop: "{{ keystone_configs | dict2items | subelements('value') }}"

- name: "Configure keystone ini"
  include_role:
    name: append_block
  vars:
    filepath: /etc/keystone/keystone.conf
    component_configs: "{{ keystone_configs }}"
- name: "Configure the keystone mysql database tables"
  become: yes
  become_user: "keystone"
  command: 'keystone-manage db_sync'
- name: "setup fernet credentials"
  command: 'keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone'
- name: "setup fernet user"
  command: 'keystone-manage credential_setup --keystone-user keystone --keystone-group keystone'
- name: "bootstrap keystone"
  command: |
    keystone-manage bootstrap --bootstrap-password {{keystone_admin_pass}} \
    --bootstrap-admin-url http://{{controller_hostname}}:5000/v3/ \
    --bootstrap-internal-url http://{{controller_hostname}}:5000/v3/ \
    --bootstrap-public-url http://{{controller_hostname}}:5000/v3/ \
    --bootstrap-region-id RegionOne
- name: "Configure httpd"
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^#ServerName www.example.com:80'
    replace: "ServerName {{controller_hostname}}"
- name: "Create Symbolic link for httpd"
  file:
    src: /usr/share/keystone/wsgi-keystone.conf
    dest: /etc/httpd/conf.d/wsgi-keystone.conf
    state: link

- name: "Restart service httpd, in all cases"
  ansible.builtin.service:
    name: httpd
    enabled: yes
    state: restarted
- name: "Create the default project"
  openstack.cloud.project:
    description: "Service Project"
    domain: default
    is_enabled: True
    name: service
    extra_specs:
      internal_alias: service
    state: present
